# Generated by Django 6.0.4 on 2026-04-17 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        ('properties', '0002_property_address_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='properties.property'),
        ),
    ]
