# Generated by Django 6.0.4 on 2026-04-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_address_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], default='sell', max_length=10),
        ),
    ]
